### ISSUE TITLE
Api\ReportSuite omitted 

### ISSUE THREAD

**Issue by atopiler** [Adobe-Marketing-Cloud/marketing-cloud-php-sdk#12]
https://github.com/Adobe-Marketing-Cloud/marketing-cloud-php-sdk/blob/master/lib/AdobeMarketingCloud/Client.php#L237

method to get Api\ReportSuite references a class that no longer exists.

**Comment by bshaffer** [comment]
Good catch.. we should remove that method all together.

We now use `$amc->getReportApi()->getElements()` and `$amc->getReportApi()->getMetrics()`, rather than the previous functions that were a part of the `Api\ReportSuite` class.
