### ISSUE TITLE
Release Tag?

### ISSUE THREAD

**Issue by davidbarratt** [Adobe-Marketing-Cloud/marketing-cloud-php-sdk#13]
There's no release tag(s) for this library, so the only thing you can do in Composer is have an open-ended dependency or specify an exact commit...
https://packagist.org/packages/adobe-marketing-cloud/marketing-cloud-php-sdk

Could you add release tags? Preferablly compatible with Semver?
http://semver.org

Thanks!

**Comment by garyr** [comment]
We've tagged the updated version as well as the legacy version. Please use 2.0.2 for the latest release. Thanks for the feedback!
