### ISSUE TITLE
queued reports dont generate ReportErrors correctly

### ISSUE THREAD

**Issue by wjaspers** [Adobe-Marketing-Cloud/marketing-cloud-php-sdk#15]
**AdobeMarkteingCloud/Api/Report.php**
```
...
proected function returnResponse($repsonse, $key = null) {
  if (isset($response['status']) && 0 === strpos($response['status'], 'error')) {
    throw new ReportError($response['statusMsg'], $response['status']);
  }
...
}
```

**sample API response (1.4)**
```
array (size=3)
  'error' => string 'period_invalid' (length=14)
  'error_description' => string 'both date and dateFrom or dateTo cannot be specified' (length=52)
  'error_uri' => string 'https://marketing.adobe.com/developer/en_US/documentation/analytics-reporting-1-4/r-reportdescription-1' (length=103)
```

One might expect that the ReportApi generates an error from any `->getReport()`|`->Report()` method.
I assume not all API responses generate a 'status' property.

**Comment by garyr** [comment]
@wjaspers, thanks for your report. I think ```returnResponse``` is left over from the old SDK and needs to be removed. If you'd like to submit a PR, feel free

**Comment by wjaspers** [comment]
Since the code i was working with hadn't version locked the SDK I needed a quick way to recoup the functionality. Wrapping and tuning a few behaviors using overridden classes gave me access to what I needed. Not so sure if other consumers of the SDK have encountered a similar issue.
