### ISSUE TITLE
Warning thrown when response is null.

### ISSUE THREAD

**Issue by kkopachev** [Adobe-Marketing-Cloud/marketing-cloud-php-sdk#24]
When doing `$report_api->queueReport($report_description);` it is possible that `HttpClient` returns `null` value as response. See https://github.com/Adobe-Marketing-Cloud/marketing-cloud-php-sdk/blob/master/lib/AdobeMarketingCloud/HttpClient.php#L218-L221
Note that exception is thrown when `json_decode` returns `null` and debug is enabled. In prod environment, debug is disabled, so value returned is `null`, despite docblock.
While that might be not a big deal by itself, this value is passed to [returnResponse](https://github.com/Adobe-Marketing-Cloud/marketing-cloud-php-sdk/blob/master/lib/AdobeMarketingCloud/Api/Report.php#L184) method on `Report` class, which expects value to be an array.

From my understanding, failure to [json]decode response would mean failed request and runtime exception has to be thrown, but looks like it will be BC break. 

Additionally to that, when calling `$report_api->Report($report_description);` it makes request to put report into a queue, server responds with invalid json, but library tries to fetch `$response['reportID']`, gets null (and throws notice), then uses this null-value to make another request to get report results, where finally gets valid response with error saying 'Report ID is required'

Ideas?

**Comment by stevja1** [comment]
Yep -- I can see that being a problem. If you'd like to put together a pull request to solve this (probably just need to throw an exception if the response is null), I'll review it. Otherwise, I'll take a look at it later and fix it.

It may take me a bit longer thought to react to this than you. Thoughts?
