### ISSUE TITLE
Version 1.4 Issues

### ISSUE THREAD

**Issue by flashbng** [Adobe-Marketing-Cloud/marketing-cloud-php-sdk#7]
I'm currently having problems with querying V1.4 of the Omniture API using this SDK, although V1.3 works just fine. Reason for the upgrade is I'm trying to utilize the ability to stack segments in the API.

When I comment out the V1.4 option, both of the var_dumps return and give me everything I need. However, when I use the option, I get NULL for both. 

Any thoughts? Code I'm using is below. 

<pre lang="PHP"><code>

<?php
require_once 'omniture_sdk/lib/AdobeDigitalMarketing/Autoloader.php';  #omniture sdk

#setup
$start_date = '2014-09-22';
$end_date = '2014-09-22';

#authentication
AdobeDigitalMarketing_Autoloader::register();
$username = 'xxxxxxx';
$secret = 'xxxxxx';
$adm = new AdobeDigitalMarketing_Client();

$adm->getHttpClient()->setOption('api_version', '1.4');
$adm->authenticate($username, $secret);

$reportApi = $adm->getReportApi();

$response = $reportApi->QueueOvertime(array(
    'reportSuiteID' => 'xxxxxx',
    'dateFrom' => date($start_date),
    'dateTo' => date($end_date),
    'metrics'  => array(
        array('id' => 'visits'),
    ),
    'segments' => '',
));

var_dump($response);

#fetch response from query
$reportId = $response['reportID'];

do {
    $report = $reportApi->getReport($reportId);
    sleep(2);
} while ($report['status'] == 'not ready');

var_dump($report);

?>

**Comment by garyr** [comment]
The newest version now supports v1.4 by default
